#!/usr/bin/env node
'use strict';

/**
 * fqe_stryker_runner.js
 *
 * Generated by `fqe init --with-mutation`. Do not hand-edit unless you know
 * why you're diverging from the canonical contract.
 *
 * Wraps Stryker mutation testing so it emits a fqe-compatible JSON line on
 * stdout. The mutation-survival rate becomes the adversarial_stats observation;
 * fqe gates it against the Wilson-CI upper bound for the configured blast
 * radius class.
 *
 * Exit codes:
 *   0 — Stryker ran, JSON emitted (verdict is fqe's call from the stats)
 *   1 — Stryker crashed before producing a report; report this as a runner FAIL
 *
 * Configure blast radius by editing the BLAST_RADIUS const below.
 */

const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

// Edit this to match the code under test. See docs/recipes/ai-test-generation.md
// for the threshold map by blast class.
// Valid values: 'outbound' (5% CI ceiling), 'mcp-read' (3%), 'mcp-write-or-financial' (1%).
// An unknown value is rejected loudly by fqe's verdict.js, not silently passed.
const BLAST_RADIUS = process.env.FQE_STRYKER_BLAST_RADIUS || 'mcp-write-or-financial';

// Anchor to the repo root the runner was spawned from. Stryker writes
// reports/mutation/mutation.json relative to its own cwd; this script must
// resolve the same path the same way. process.cwd() is what fqe's orchestrator
// sets when spawning runners, and Stryker inherits that.
const REPORT_PATH = path.resolve(process.cwd(), 'reports', 'mutation', 'mutation.json');

function fail(msg) {
  console.error(`fqe-stryker-runner: ${msg}`);
  process.exit(1);
}

// 1. Run Stryker, ask for JSON reporter
const stryker = spawnSync('npx', ['stryker', 'run', '--reporters', 'json,progress'], {
  encoding: 'utf8',
  timeout: 14 * 60 * 1000,
  stdio: ['ignore', 'inherit', 'inherit'],
});

// Stryker exits 1 when below break threshold; 0 when above. Either is fine
// because we re-report the rate to fqe and let fqe do the threshold check.
if (stryker.status !== 0 && stryker.status !== 1) {
  fail(`Stryker crashed (exit ${stryker.status})`);
}

if (!fs.existsSync(REPORT_PATH)) {
  fail(`Stryker did not produce ${REPORT_PATH}`);
}

// 2. Parse the report
// Mutant statuses Stryker emits: Killed, Survived, Timeout, NoCoverage, Ignored,
// CompileError, RuntimeError. We treat:
//   - Killed: pass (test caught it)
//   - Survived: fail (test missed it)
//   - Timeout: fail (test hung; not killed in any useful sense)
//   - NoCoverage: fail (test suite did not even exercise the mutated line)
//   - Ignored / CompileError / RuntimeError: skip (not measurement-relevant)
// Bucketing Timeout + NoCoverage with Survived prevents a "looks-good" score
// from hiding tests that hang or skip the mutated branch entirely.
const report = JSON.parse(fs.readFileSync(REPORT_PATH, 'utf8'));
const allMutants = Object.values(report.files || {}).flatMap((f) => f.mutants || []);
const killed = allMutants.filter((m) => m.status === 'Killed').length;
const surviving = allMutants.filter((m) =>
  m.status === 'Survived' || m.status === 'Timeout' || m.status === 'NoCoverage'
).length;
const survived = surviving;   // legacy name kept for the emit block below
const total = killed + survived;

if (total === 0) {
  fail('Stryker report has zero measurable mutants. Check stryker.conf.json mutate patterns.');
}

// 3. Compute Wilson 95% CI for the survival rate
// (fqe's own wilson helper if available; fallback to inline math)
let ci95 = null;
try {
  const wilson = spawnSync('fqe', ['wilson', String(survived), String(total)], {
    encoding: 'utf8',
    timeout: 5000,
  });
  if (wilson.status === 0 && wilson.stdout) {
    ci95 = JSON.parse(wilson.stdout).ci_95;
  }
} catch (_) { /* fall through to inline */ }

if (!ci95) {
  // Inline Wilson 95% CI fallback
  const z = 1.959963984540054;
  const p = survived / total;
  const z2 = z * z;
  const denom = 1 + z2 / total;
  const center = (p + z2 / (2 * total)) / denom;
  const half = (z * Math.sqrt(p * (1 - p) / total + z2 / (4 * total * total))) / denom;
  ci95 = [Math.max(0, center - half), Math.min(1, center + half)];
}

// 4. Emit the fqe JSON line
const out = {
  runner: 'stryker-mutation',
  exit_code: 0,
  adversarial_stats: [
    {
      runner: 'stryker-mutation',
      n: total,
      successes: survived,
      ci_95: ci95,
      blast_radius: BLAST_RADIUS,
    },
  ],
};
console.log(JSON.stringify(out));
process.exit(0);
