#!/usr/bin/env bash
#
# fqe test-author runner (generated by `fqe init --with-qodo`).
#
# Wraps an AI test AUTHOR so it runs as an fqe runner. The author is OPTIONAL
# and PLUGGABLE. The mutation gate (the stryker-mutation runner) is what blocks
# a merge. This runner is required:false, so it never blocks on its own.
#
# IMPORTANT: the original open-source `qodo-cover` package is archived and is
# NOT installable from PyPI. Do not `pip install qodo-cover`. Wire your chosen
# author through FQE_TEST_AUTHOR_CMD:
#   - qodo-ai/qodo-ci   (the maintained Action / CLI)
#   - Qodo's hosted product
#   - any LLM-driven generator you control
#
# Env:
#   FQE_TEST_AUTHOR_CMD   full command that runs your author (writes tests to the tree)
#   ANTHROPIC_API_KEY     LLM key your author uses, if it needs one
#
# With no FQE_TEST_AUTHOR_CMD set this is a clean no-op: it logs that no author
# is wired and exits 0, so the gate still runs on whatever tests exist. See
# docs/recipes/ai-test-generation.md.

set -uo pipefail

if [ -z "${FQE_TEST_AUTHOR_CMD:-}" ]; then
  echo "fqe test-author: no FQE_TEST_AUTHOR_CMD configured; skipping generation (gate-only)."
  echo "  Wire qodo-ci, hosted Qodo, or your own generator. The archived qodo-cover does not install."
  echo '{"runner":"qodo-cover","exit_code":0}'
  exit 0
fi

if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -z "${OPENAI_API_KEY:-}" ]; then
  echo "::warning::fqe test-author: no LLM key set (ANTHROPIC_API_KEY/OPENAI_API_KEY); your author may fail."
fi

echo "fqe test-author: running configured author"
# The author writes tests into the working tree. The mutation gate decides if
# they are good. A failing author must NOT block the merge, so swallow its exit.
bash -c "${FQE_TEST_AUTHOR_CMD}" || echo "::warning::fqe test-author exited non-zero; continuing (the gate decides)."

echo '{"runner":"qodo-cover","exit_code":0}'
exit 0
