#!/usr/bin/env bash
#
# fqe_qodo_runner.sh
#
# Generated by `fqe init --with-qodo`. Do not hand-edit unless you know
# why you're diverging from the canonical contract.
#
# Wraps Qodo Cover so it runs as a fqe runner. Qodo Cover generates AI test
# candidates, filters them mechanically (compile + run + dedupe) via the
# Meta TestGen-LLM pipeline, and commits the survivors. fqe then re-runs
# Stryker mutation testing on the new suite to verify the AI-generated
# tests actually catch bugs.
#
# Required env vars:
#   ANTHROPIC_API_KEY    — Claude API key (preferred). Finexio's existing key.
#   OPENAI_API_KEY       — fallback if you really want OpenAI. Default is Claude.
#
# Optional env vars:
#   FQE_QODO_MODEL              — defaults to anthropic/claude-opus-4-7
#   FQE_QODO_SOURCE_GLOB        — defaults to src/ + lib/
#   FQE_QODO_TEST_DIR           — defaults to test/
#   FQE_QODO_TARGET_COVERAGE    — defaults to 85
#   FQE_QODO_MAX_ITERATIONS     — defaults to 3

set -euo pipefail

MODEL="${FQE_QODO_MODEL:-anthropic/claude-opus-4-7}"
SOURCE_GLOB="${FQE_QODO_SOURCE_GLOB:-src/}"
TEST_DIR="${FQE_QODO_TEST_DIR:-test/}"
TARGET_COVERAGE="${FQE_QODO_TARGET_COVERAGE:-85}"
MAX_ITERATIONS="${FQE_QODO_MAX_ITERATIONS:-3}"

# Provider key check: at least one must be set.
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -z "${OPENAI_API_KEY:-}" ]; then
  echo "::error::fqe_qodo_runner: neither ANTHROPIC_API_KEY nor OPENAI_API_KEY is set"
  echo "::error::Add ANTHROPIC_API_KEY to repo Settings, Secrets and variables, Actions"
  exit 1
fi

# Pin Qodo Cover to a known-good version. Bump as needed.
QODO_COVER_VERSION="${FQE_QODO_VERSION:-0.4.0}"

if ! command -v cover-agent >/dev/null 2>&1; then
  pip install --quiet "qodo-cover==${QODO_COVER_VERSION}"
fi

# Run cover-agent against the changed files. fqe's orchestrator passes
# the changed-files list via FQE_CHANGED_FILES if available, else we
# fall back to the configured source glob.
TARGET="${FQE_CHANGED_FILES:-${SOURCE_GLOB}}"

cover-agent \
  --source-file-path "${TARGET}" \
  --test-file-path "${TEST_DIR}" \
  --model "${MODEL}" \
  --desired-coverage "${TARGET_COVERAGE}" \
  --max-iterations "${MAX_ITERATIONS}" \
  --use-report-coverage-feature-flag

# Qodo Cover commits the generated tests directly to the working tree.
# fqe will pick them up on the next Stryker run (the mutation gate is
# what actually decides whether the tests are good).
#
# Emit a fqe JSON line so the orchestrator records this as a runner pass.
cat <<JSON
{"runner":"qodo-cover","exit_code":0}
JSON
