'use strict';

/**
 * fqe init — one-command repo bootstrap.
 *
 * Writes the files needed to deploy the gate on a Finexio repo:
 *   .fqe.yml                                — runner config (sample)
 *   .github/workflows/fqe-quality.yml        — main CI gate
 *   .github/workflows/fqe-second-approve.yml — bypass-rate unblock
 *   .github/fqe-bypass-allowlist.yml         — who can bypass (default: current gh user)
 *   .github/fqe-second-reviewers.yml         — who can second-approve (empty by default)
 *   .github/fqe-state/.gitkeep               — ensures the state dir exists
 *
 * Idempotent: refuses to overwrite existing files unless --force.
 * Returns { written: [...], skipped: [...] }.
 *
 * Templates are inlined so the npm package is self-contained.
 */

const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

/**
 * Additional templates wired by `--with-mutation`. See the
 * docs/recipes/ai-test-generation.md for the full recipe.
 */
const MUTATION_RUNNER_BLOCK = `
  # Wired by 'fqe init --with-mutation'. Reads Stryker's mutation report and
  # emits Wilson-CI-bounded adversarial_stats. blast_radius defaults to
  # mcp-write-or-financial (1% survival ceiling) which is correct for code
  # that touches money or state. Re-tune via FQE_STRYKER_BLAST_RADIUS env var.
  stryker-mutation:
    command: "node"
    args: ["scripts/fqe_stryker_runner.js"]
    when: ["**/*.js", "**/*.ts", "test/**", "stryker.conf.json"]
    required: true
    timeout_ms: 900000
`;

const FILES = {
  '.fqe.yml': `# Finexio Quality Engine - repo config
# Each runner declares: command, args, when (glob patterns), required, always_run
# Edit to match this repo's actual runners. Empty config = no runners = always PASS.
#
# Examples:
#
# runners:
#   web:
#     command: "npx"
#     args: ["playwright", "test"]
#     when: ["**/*.tsx", "**/*.jsx", "**/*.html"]
#     required: true
#
#   excel:
#     command: "python3"
#     args: ["scripts/fqe_excel_diff.py"]
#     when: ["**/*.xlsx"]
#     required: true
#
#   outbound:
#     command: "vale"
#     args: ["--config", ".vale.ini", "templates/"]
#     when: ["**/templates/**", "**/emails/**"]
#     required: true

runners: {}
`,

  '.github/workflows/fqe-quality.yml': `# Finexio Quality Engine - main CI gate
# Generated by 'fqe init'. Edit .fqe.yml to configure runners.
#
# Architectural invariants (verbatim from PLAN-v6):
#   1. No identity from attacker-writable sources (Events API only)
#   2. No LLM in the verdict path (verdict.js)
#   3. No required state only in PR branch (artifacts + Check Run outputs)

name: FQE Quality
on:
  pull_request:
    branches: [__FQE_DEFAULT_BRANCH__]

permissions:
  contents: read
  pull-requests: read
  checks: write
  actions: read

jobs:
  fqe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install fqe CLI from booyajones/finexio-skills (TAG-pinned)
        run: |
          set -euo pipefail
          # Supply-chain hardening: clone is pinned to a specific tag, not HEAD.
          # To update fqe, push a new tag in finexio-skills and re-run fqe init.
          # When ghcr.io/booyajones/fqe:0.1 is published with cosign verify,
          # this entire step can be replaced with: container: ghcr.io/booyajones/fqe:0.1
          FQE_TAG="fqe-v0.1.0"
          git clone --depth=1 --branch "$FQE_TAG" \\
            https://github.com/booyajones/fqe.git /tmp/fqe-src
          cd /tmp/fqe-src/cli
          npm install --omit=dev
          chmod +x bin/fqe.js
          sudo ln -sf "$PWD/bin/fqe.js" /usr/local/bin/fqe
          fqe version

      - name: Install yq (Mike Farah v4) with SHA256 verification
        run: |
          set -euo pipefail
          # Supply-chain hardening: SHA256-verified download. If GitHub releases
          # ever served a tampered binary, sha256sum -c would fail closed.
          YQ_SHA256=654d2943ca1d3be2024089eb4f270f4070f491a0610481d128509b2834870049
          sudo wget -q "https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64" -O /usr/local/bin/yq
          echo "$YQ_SHA256  /usr/local/bin/yq" | sha256sum -c -
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Check bypass eligibility (server-authoritative)
        id: bypass-eligibility
        env:
          GH_TOKEN: \${{ github.token }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
          REPO: \${{ github.repository }}
        run: |
          set -euo pipefail
          LABELS=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json labels --jq '[.labels[].name] | join(",")')
          if ! echo ",$LABELS," | grep -q ',fqe-bypass,'; then
            echo "bypass=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Identity from Events API (server-recorded), not from any file
          BYPASS_ACTOR=$(gh api \\
            "/repos/$REPO/issues/$PR_NUMBER/events" --paginate \\
            --jq '[.[] | select(.event=="labeled" and .label.name=="fqe-bypass")] | last | .actor.login')
          if [ -z "$BYPASS_ACTOR" ] || [ "$BYPASS_ACTOR" = "null" ]; then
            echo "::error::fqe-bypass label present but no labeled event found"
            exit 1
          fi
          BASE_SHA='\${{ github.event.pull_request.base.sha }}'
          ALLOWLIST=$(git show "$BASE_SHA:.github/fqe-bypass-allowlist.yml" | yq '.allowed_actors[]' -)
          if ! echo "$ALLOWLIST" | grep -qx "$BYPASS_ACTOR"; then
            echo "::error::Actor '$BYPASS_ACTOR' not in fqe-bypass allowlist (at base commit)"
            exit 1
          fi
          echo "bypass=true" >> "$GITHUB_OUTPUT"
          echo "bypass_actor=$BYPASS_ACTOR" >> "$GITHUB_OUTPUT"

      - name: Generate bypass receipt
        if: steps.bypass-eligibility.outputs.bypass == 'true'
        run: |
          set -euo pipefail
          mkdir -p out
          fqe receipt generate-bypass \\
            --commit '\${{ github.event.pull_request.head.sha }}' \\
            --pr '\${{ github.event.pull_request.number }}' \\
            --actor '\${{ steps.bypass-eligibility.outputs.bypass_actor }}' \\
            --requester-source github_events_api_v3 \\
            --events-url 'https://github.com/\${{ github.repository }}/pull/\${{ github.event.pull_request.number }}' \\
            --output out/

      - name: Run fqe (normal path)
        if: steps.bypass-eligibility.outputs.bypass != 'true'
        run: |
          set -euo pipefail
          mkdir -p out
          fqe run --full \\
            --commit '\${{ github.event.pull_request.head.sha }}' \\
            --base '\${{ github.event.pull_request.base.sha }}' \\
            --pr '\${{ github.event.pull_request.number }}' \\
            --output out/ || true
          if [ ! -f out/QA-RESULT.yml ]; then
            echo "::error::fqe run did not produce a receipt"
            exit 1
          fi

      - name: Upload receipt as workflow artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-receipt-\${{ github.event.pull_request.head.sha }}
          path: |
            out/QA-RESULT.yml
            out/QA-RESULT.md
          retention-days: 90

      - name: Determine fqe/pass state from verdict
        if: always()
        id: pass-state
        run: |
          set -euo pipefail
          if [ ! -f out/QA-RESULT.yml ]; then
            echo "state=failure" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          STATE=$(fqe status print out/QA-RESULT.yml | jq -r .check_state)
          echo "state=$STATE" >> "$GITHUB_OUTPUT"

      - name: Publish fqe/pass Check Run
        if: always()
        env:
          GH_TOKEN: \${{ github.token }}
          GITHUB_REPOSITORY: \${{ github.repository }}
        run: |
          set -euo pipefail
          if [ -f out/QA-RESULT.md ]; then
            BODY=$(head -c 65000 out/QA-RESULT.md)
          else
            BODY="No receipt produced"
          fi
          fqe status publish \\
            --check fqe/pass \\
            --commit '\${{ github.event.pull_request.head.sha }}' \\
            --state '\${{ steps.pass-state.outputs.state }}' \\
            --output-text "$BODY"

      - name: Tally + compute rolling bypass rate
        if: always()
        id: bypass-rate
        env:
          STATE_DIR: .github/fqe-state
        run: |
          set -euo pipefail
          mkdir -p "$STATE_DIR"
          fqe bypass-tally append-run \\
            --state-dir "$STATE_DIR" \\
            --pr '\${{ github.event.pull_request.number }}' \\
            --commit '\${{ github.event.pull_request.head.sha }}'
          if [ "\${{ steps.bypass-eligibility.outputs.bypass }}" = "true" ]; then
            fqe bypass-tally append-bypass \\
              --state-dir "$STATE_DIR" \\
              --actor '\${{ steps.bypass-eligibility.outputs.bypass_actor }}' \\
              --pr '\${{ github.event.pull_request.number }}' \\
              --commit '\${{ github.event.pull_request.head.sha }}'
          fi
          RATE=$(fqe bypass-tally rate --state-dir "$STATE_DIR" --window-days 14 --format scalar)
          echo "rate=$RATE" >> "$GITHUB_OUTPUT"

      - name: Publish fqe/second-reviewer-required Check Run
        if: always()
        env:
          GH_TOKEN: \${{ github.token }}
          GITHUB_REPOSITORY: \${{ github.repository }}
        run: |
          set -euo pipefail
          RATE='\${{ steps.bypass-rate.outputs.rate }}'
          if awk -v r="$RATE" 'BEGIN{exit !(r > 0.10)}'; then
            fqe status publish \\
              --check fqe/second-reviewer-required \\
              --commit '\${{ github.event.pull_request.head.sha }}' \\
              --state failure \\
              --description "Rolling bypass rate $RATE exceeds 10%; second reviewer required"
          else
            fqe status publish \\
              --check fqe/second-reviewer-required \\
              --commit '\${{ github.event.pull_request.head.sha }}' \\
              --state success \\
              --description "Bypass rate $RATE within tolerance"
          fi
`,

  '.github/workflows/fqe-second-approve.yml': `# Finexio Quality Engine - second-approve workflow
# Triggers on PR label fqe-second-approved. Validates the approver via Events API.

name: FQE Second Approve
on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  approve:
    if: github.event.label.name == 'fqe-second-approved'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/booyajones/fqe:0.1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.base.sha }}

      - name: Identify both actors via Events API
        id: actors
        env:
          GH_TOKEN: \${{ github.token }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
          REPO: \${{ github.repository }}
        run: |
          set -euo pipefail
          BYPASS_ACTOR=$(gh api \\
            "/repos/$REPO/issues/$PR_NUMBER/events" --paginate \\
            --jq '[.[] | select(.event=="labeled" and .label.name=="fqe-bypass")] | last | .actor.login')
          if [ -z "$BYPASS_ACTOR" ] || [ "$BYPASS_ACTOR" = "null" ]; then
            echo "::error::Cannot find original fqe-bypass label event"
            exit 1
          fi
          APPROVER='\${{ github.event.sender.login }}'
          echo "bypass_actor=$BYPASS_ACTOR" >> "$GITHUB_OUTPUT"
          echo "approver=$APPROVER" >> "$GITHUB_OUTPUT"

      - name: Validate approver (allowlist + same-actor rule)
        env:
          BYPASS_ACTOR: \${{ steps.actors.outputs.bypass_actor }}
          APPROVER: \${{ steps.actors.outputs.approver }}
        run: |
          set -euo pipefail
          if ! yq '.allowed_actors[]' .github/fqe-second-reviewers.yml | grep -qx "$APPROVER"; then
            echo "::error::Approver '$APPROVER' not in second-reviewer allowlist (at base commit)"
            exit 1
          fi
          if [ "$APPROVER" = "$BYPASS_ACTOR" ]; then
            echo "::error::Second approver '$APPROVER' cannot be the bypass requester '$BYPASS_ACTOR'"
            exit 1
          fi

      - name: Re-emit fqe/second-reviewer-required = success
        env:
          GH_TOKEN: \${{ github.token }}
          GITHUB_REPOSITORY: \${{ github.repository }}
        run: |
          fqe status publish \\
            --check fqe/second-reviewer-required \\
            --commit '\${{ github.event.pull_request.head.sha }}' \\
            --state success \\
            --description "Approved by \${{ steps.actors.outputs.approver }} (bypass by \${{ steps.actors.outputs.bypass_actor }})"
`,

  '.github/fqe-bypass-allowlist.yml': `# Who can add the 'fqe-bypass' label to skip the gate.
# The fqe-quality workflow looks up the LABEL ADDER (from GitHub Events API,
# server-authoritative) against this list at the PR's BASE commit, so a PR
# cannot add itself to this allowlist.
#
# Modifying this file is itself a PR that goes through the gate.

allowed_actors:
  - __FQE_DEFAULT_ACTOR__
`,

  '.github/fqe-second-reviewers.yml': `# Who can add 'fqe-second-approved' to unblock when rolling bypass rate > 10%.
# Approver must NOT be the same person who added 'fqe-bypass' (Events API check).
# Approver must be in this list at the PR's BASE commit.
#
# Add real reviewers here. Single-entry is acceptable for a solo operator but
# means same-actor rejection becomes the only collusion defense.

allowed_actors: []
`,

  '.github/fqe-state/.gitkeep': '',
};

/**
 * Detect the current GitHub actor via `gh api user`. Used to seed the
 * bypass allowlist. Returns null if gh isn't installed or not authenticated.
 */
function currentGhActor() {
  try {
    const r = spawnSync('gh', ['api', 'user', '--jq', '.login'], {
      encoding: 'utf8',
      timeout: 10000,
    });
    if (r.status === 0 && r.stdout) {
      return r.stdout.trim();
    }
  } catch (_) { /* fall through */ }
  return null;
}

/**
 * Detect the default branch of the git repo at `dir`. Tries (in order):
 *   1. git symbolic-ref refs/remotes/origin/HEAD
 *   2. gh repo view --json defaultBranchRef
 *   3. Fall back to 'main'
 */
function detectDefaultBranch(dir) {
  // Try git symbolic-ref (works offline if origin/HEAD is set)
  try {
    const r = spawnSync('git', ['-C', dir, 'symbolic-ref', '--short', 'refs/remotes/origin/HEAD'], {
      encoding: 'utf8',
      timeout: 5000,
    });
    if (r.status === 0 && r.stdout) {
      const ref = r.stdout.trim();
      // "origin/main" -> "main"
      const m = ref.match(/^origin\/(.+)$/);
      if (m) return m[1];
    }
  } catch (_) { /* fall through */ }
  // Try gh repo view (works for cloned repos with remote origin)
  try {
    const r = spawnSync('gh', ['repo', 'view', '--json', 'defaultBranchRef', '--jq', '.defaultBranchRef.name'], {
      encoding: 'utf8',
      timeout: 10000,
      cwd: dir,
    });
    if (r.status === 0 && r.stdout) {
      return r.stdout.trim();
    }
  } catch (_) { /* fall through */ }
  return 'main';
}

/**
 * Read a packaged template file (under cli/templates/). Returns null if missing,
 * which is how we tell init() to skip mutation wiring on installs that didn't
 * ship the templates dir.
 */
function readPackagedTemplate(name) {
  const candidates = [
    path.join(__dirname, '..', 'templates', name),
    path.join(__dirname, '..', '..', 'cli', 'templates', name),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8');
  }
  return null;
}

/**
 * @param {{ dir: string, force?: boolean, actor?: string, withMutation?: boolean }} opts
 */
function init(opts) {
  const dir = path.resolve(opts.dir || process.cwd());
  if (!fs.existsSync(dir)) {
    throw new Error(`init: target dir does not exist: ${dir}`);
  }
  // Detect a repo: must contain .git OR be passed explicitly via --force
  const isRepo = fs.existsSync(path.join(dir, '.git'));
  if (!isRepo && !opts.force) {
    throw new Error(`init: ${dir} is not a git repo. Run 'git init' first or pass --force.`);
  }

  const actor = opts.actor || currentGhActor() || 'REPLACE_WITH_GITHUB_LOGIN';
  const defaultBranch = opts.defaultBranch || detectDefaultBranch(dir);

  const written = [];
  const skipped = [];
  const notes = [];

  // Build per-invocation FILES so we can conditionally append the mutation runner
  // to .fqe.yml WITHOUT mutating the module-level FILES constant.
  const dynamicFiles = { ...FILES };

  if (opts.withMutation) {
    const strykerRunner = readPackagedTemplate('fqe_stryker_runner.js');
    const strykerConf = readPackagedTemplate('stryker.conf.json');
    if (!strykerRunner || !strykerConf) {
      notes.push('--with-mutation requested but templates/ not found on disk. Skipped mutation wiring.');
    } else {
      // Inject runner block into .fqe.yml. The base template ends with
      // "runners: {}" which means "no runners"; we replace that with
      // "runners:\n  stryker-mutation: ..." so YAML parses as a non-empty map.
      const baseYml = dynamicFiles['.fqe.yml'];
      const newYml = baseYml.replace(
        /\nrunners:\s*\{\}\s*\n?$/m,
        `\nrunners:${MUTATION_RUNNER_BLOCK}`
      );
      dynamicFiles['.fqe.yml'] = newYml;
      dynamicFiles['scripts/fqe_stryker_runner.js'] = strykerRunner;
      dynamicFiles['stryker.conf.json'] = strykerConf;
    }
  }

  for (const [relPath, template] of Object.entries(dynamicFiles)) {
    const fullPath = path.join(dir, relPath);
    const exists = fs.existsSync(fullPath);
    if (exists && !opts.force) {
      skipped.push(relPath);
      continue;
    }
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    const content = template
      .replace(/__FQE_DEFAULT_ACTOR__/g, actor)
      .replace(/__FQE_DEFAULT_BRANCH__/g, defaultBranch);
    fs.writeFileSync(fullPath, content);
    written.push(relPath);
  }

  // If we wired mutation, leave a breadcrumb for the engineer about what's next
  if (opts.withMutation && written.includes('scripts/fqe_stryker_runner.js')) {
    notes.push('Next: npm install --save-dev @stryker-mutator/core, then commit + open PR. See docs/recipes/ai-test-generation.md.');
  }

  return { written, skipped, actor, defaultBranch, dir, notes };
}

module.exports = { init, FILES, currentGhActor, readPackagedTemplate, MUTATION_RUNNER_BLOCK };
